apiVersion: v1 
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example-app
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
